server.port=8081

spring.application.name=Taller Rendimiento WebFlux

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/bd_rendimiento
spring.r2dbc.username=postgres
spring.r2dbc.password=1234

# -----------------------------------------------------
# CONFIGURACIÓN OPTIMIZADA DEL CONNECTION POOL (R2DBC)
# -----------------------------------------------------

spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=100
spring.r2dbc.pool.max-idle-time=5m
spring.r2dbc.pool.max-life-time=30m
spring.r2dbc.pool.max-create-connection-time=10s
spring.r2dbc.pool.max-acquire-time=1s
spring.r2dbc.pool.validation-query=SELECT 1

# -----------------------------------------------------
# CONFIGURACIÓN DE MONITOREO Y LOGGING
# -----------------------------------------------------

management.endpoints.web.exposure.include=*
management.metrics.enable.r2dbc=true
management.metrics.tags.application=taller-rendimiento-WebFlux

logging.level.root=INFO
logging.level.co.edu.unbosque.tallerrendimientowebflux=DEBUG
logging.level.io.r2dbc.postgresql.query=DEBUG